In [1]:
import numpy as np
arr = np.arange(1,82).reshape(9,9)
arr

m=[]

for i in range(0,9,3):
    for j in range(0,9,3):
        t=np.vstack((arr[i][j:j+3] , arr[i+1][j:j+3] , arr[i+2][j:j+3]))
        m.append(t.max())
        #print(t)
        #print("Max \n: ",t.max())
        #print('-'*50)
    #print('')
print(np.array(m).reshape(3,3)) 

[[21 24 27]
 [48 51 54]
 [75 78 81]]
